[package]
name = "business"
version = "0.1.0"
edition = "2018"

[dependencies]
domain = { path="../domain" }
server_lib = { path="../server_lib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.48"
