[package]
name = "server_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server_lib = { path="../server_lib" }
lazy_static = "1.4.0"