[package]
name = "domain"
version = "0.1.0"
edition = "2018"

[dependencies]
server_lib = { path="../server_lib" }
serde = { version = "1.0", features = ["derive"] }

[dependencies.mongodb]
version = "2.0.0-beta.2"
default-features = false
features = ["sync"]
